### ISSUE TITLE
Context Equivalent of RaiseIntent

### ISSUE THREAD

**Issue by sgd2z** [ChartIQ/FDC3#3]
### Use Case:
User selects intent as opposed to intent being required in the API call. 

For example: 
User clicks on a contact. With a contact, the user can have multiple possible Intents. So the user can select one of those intents - "StartChat", "Email", "StartCall, "AddToAddressBook", "OpenInCRM" etc.

### Workflow Description
User clicks on a UI representation of a context
System shows UI with possible Intents/Resolvers
User selects an Intent then raiseIntent is automatically called with the intent and context

### Workflow Examples
User clicks on a contact
System shows a UI to select possible intents and Applications that can resolve these intents.
Caller gets back response data which includes the selected Intent & IntentResolution

### Additional Information
This is currently difficult because it requires two API calls:
- findIntentsByContext 
- raiseIntent 
As an app developer it is not immediately obvious how to combine these APIs in a convenient way. findIntentsByContext does result in a list of intents and then the developer could potentially call that, get the response and then show a UI and raiseIntent from that UI. It would be much more convenient to have that dealt with under the hood so it becomes the responsibility of the desktop integrator as opposed to the app developer.

### Potential solutions
Modify raiseIntent to work without an intent specified:
e.g. 
```
raiseIntent(null, context): Promise<IntentResolution>;
```

Add a new API:
```
raiseContext(context): Promise<IntentResolution>;
```

**Comment by kriswest** [comment]
Perhaps add a 3rd step to the workflow description: "User selects an Intent then raiseIntent is automatically called with the intent and context".

Perhaps prepend "raiseContext: " to the name of the issue.

Otherwise all good with me.

**Comment by sean-ciq** [comment]
Ditto to what @kriswest said. 

Without being too explicit in the proposal, should `raiseContext` return an array of IntentResolution since context has a one-to-many relationship with Intents?

If you think that's too explicit, I would at least specify that IntentResolution is the return type for `raiseContext`.

**Comment by sgd2z** [comment]
I updated with the added step to the Workflow example. The 1-many relationship with raising intents is something Watson also proposed. If that is something that has a practical application without making things too complex, I'll add it. But generally in other systems, I haven't seen multiple actions on the same context selection.

**Comment by sgd2z** [comment]
Didn't have the opportunity to make a video but here is the problem described in pictures:
User clicks on a Symbol and is shown potential intents (find intents by context). This is something an app developer can do with FDC3. One problem is that every app developer will make something different, making a desktop integration platform not look standard:
![image](https://user-images.githubusercontent.com/18012933/88082355-afc50100-cb4f-11ea-93c9-93ef242cc17b.png)

Now, let's say there are multiple apps that can resolve that intent. The app developer now needs to either make their menu complicated. In the actions on the above menu - Buy with AppX, Buy with AppY. Now we get to the third problem. What if there are several instances of the app open. How does the developer let the user select an open instance vs opening a new instance? The only viable option the developer has is to show the simple menu and then just call raiseIntent and let the desktop integration platform deal with the intent.

Now once the integration platform gets the Intent, it will show up another intent resolver, which will finally allow the user to perform the action they requested with the proper app or app instance.
![image](https://user-images.githubusercontent.com/18012933/88083598-42b26b00-cb51-11ea-92a0-17f9863996f7.png)

Instead if the app developer, could call raiseContext and the desktop integration platform would handle it from that point, the wouldn't need multiple API calls, the user experience would be seamless and consistent across applications and we could deal with all of intent selection and resolver selection in a single consistent UI.
