### ISSUE TITLE
Add additional properties to AppMetadata type

### ISSUE THREAD

**Issue by sean-ciq** [ChartIQ/FDC3#4]
### Use Case:
An application developer, in a situation where more than one App Directory exists and the names of applications are not unique, needs more information about applications returned from `findIntent()` or `findIntentsByContext()` to successfully raise an intent to a specified `target`. We recommend bringing in fields from the AppD application definition that differentiate different apps with the same name:
- `appId`: the fully qualified appID differentiates based on version and the appDirectory and hence should be globally unique
- `version`: the value that differentiates different copies of an app within a single app directory 

### Workflow Description
1. Application calls `findIntent()` or `findIntentsByContext()`
2. Application receives a response containing a list of AppIntent objects, themselves containing an AppMetadata object for each application that details are being returned on.
3. AppMetadata objects contain values that can *uniquely* identify each app (given that multiple AppD's may be in use, each of which could contain multi[le versions of an application with a single `name` value).

### Workflow Examples
1. User clicks on a contact
2. UI displays the available applications.
3. There are multiple applications available with the name "Messenger"
4. The user selects any "Messenger" from the UI
5. Instead of passing a `name` value, the application passes an AppMetadata object containing an `appId` value or `name` and `version`, uniquely identifying the app
6. Desired app version is launched.

### Additional Information
Note the following definitions in the AppD specification for an application record:

> `name`: The name of the application. The name should be unique within an FDC3 App Directory instance. The exception to the uniqueness constraint is that an App Directory can hold definitions for multiple versions of the same app. The same appName could occur in other directories. We are not currently specifying app name conventions in the document.
> `version`: Version of the application. This allows multiple app versions to be defined using the same app name. This can be a triplet but can also include things like 1.2.5 (BETA)

Integrating additional properties defined in the App D specification provides an additional way for applications to determine and specify intent targets. The argument for returning the entire AppMetadata object from `findIntents()` & `findIntentsByContext()` and others is based upon deference to the application. If an application receives a list of available apps, there is currently no identifier other than the `name` property. This inability to properly identify other applications by one or more properties breaks down when:
- there are multiple app directories
- there are multiple versions of an app within the app directory 

### Proposed Additions

Current `AppMetadata` interface:
```Typescript
interface AppMetadata {
  name: string;
  title?: string;
  tooltip?: string;
  description?: string;
  icons?: Array<string>;
  images?: Array<string>;
}
```

New interface:
```Typescript
interface AppMetadata {
  name: string;
  appId?: string;
  version?: string;
  title?: string;
  tooltip?: string;
  description?: string;
  icons?: Array<string>;
  images?: Array<string>;
}
```
If the additional properties are added to AppMetadata, the following changes should be considered for consistency of standards:

Current open() interface:
`open(name: string, context?: Context): Promise<void>;`

Proposed changes:
`open(appMetadata: AppMetadata, context?: Context, context?: Context): Promise<void>;`

Current raiseIntent() interface:
`raiseIntent(intent: string, context: Context, target?: string): Promise<IntentResolution>;`

Proposed changes:
`raiseIntent(intent: string, context: Context, target?: string | AppMetadata): Promise<IntentResolution>;`

**Comment by sean-ciq** [comment]
Working through this issue again, I now recognize the value in having the entire AppMetadata object returned from `findIntents` & `findIntentsByContext`. Simply because an application may need more indentifying information before calling `raiseIntent` or `open`.

I'm still a little anxious about proposing that that `target` parameter be more than just a string. I could see a small object being  passed, but I think it comes down to a question of how `appId` is defined in the App Directory Spec. By this I mean, that I don't know if an `appId` is going to be unique for each version of the same application.

**Comment by kriswest** [comment]
I think you also need to make a proposal for the update to the [fdc3.open](https://fdc3.finos.org/docs/1.1/api/ref/DesktopAgent#open) API signature:
```open(name: string, context?: Context): Promise<void>;```
as it uses that 'name'. Theres a number of ways it could work - the simplest might be to have an alternative signature based on passing the whole AppMetadata Object:
```open(appMetadata: AppMetadata, context?: Context): Promise<void>;```
The desktop agent can then use appId and failover to name.

Otherwise this looks great and ready for submission

**Comment by kriswest** [comment]
[raiseIntent](https://fdc3.finos.org/docs/1.1/api/ref/DesktopAgent#raiseintent)'s target could work that way also:
```raiseIntent(intent: string, context: Context, target?: string | AppMeta): Promise<IntentResolution>;```
however it only has fields (before or after your proposed change) to identify an app, rather than an instance of an app. To get to the instance we'd need a new 'instanceId' field in the AppMetadata object. This could be defined or implementation specific (better defined, but not essential).

**Comment by sean-ciq** [comment]
I've added both to the proposal.

**Comment by kriswest** [comment]
I made a minor copy change to the last point of both Workflow description and examples to match up with that

**Comment by kriswest** [comment]
Got rid of the 'String' and added reference to AppMetadata in workflow examples, can't edit your issue on the FDC3 github repo however @sean-ciq

**Comment by sean-ciq** [comment]
updated. Thank you
