### ISSUE TITLE
Ready Event before FDC3 API can be called

### ISSUE THREAD

**Issue by sgd2z** [ChartIQ/FDC3#5]
## Enhancement Request
We would like to propose adding a ready event before FDC3 API can be called and a ready state global.

```
function fdc3stuff() {
  // Make some fdc3 API calls here
}

if (window.fdc3Ready) {
  fdc3stuff();
} else {
  window.addEventListener("fdc3Ready", fdc3stuff);
}
```

### Use Case:
Calling the DesktopAgent API generally requires that the Desktop Agent is ready to broadcast/receive data which generally relies on some underlying infrastructure to be ready. 

For example: 
In a Desktop Integration Platform like Finsemble where communication happens between different components, it is necessary for the communication channels of the platform to be ready before fdc3 API can be called. Also, the fdc3 API itself relies on a a service or other infrastructure outside the component, which needs to be ready before it can be used. So calling any fdc3 API as soon as a component starts up might fail.

Just adding a ready event however is not enough because sometimes, the ready event has already occurred before any checks are made. So we would like to propose adding a global ready state that can be checked in addition to the ready event.

**Comment by kriswest** [comment]
Looks good to me, however, I'd include a proposal for how a ready state patten should work (in conjunction with the event listener). 

I've seen other implementations have similar issues, e.g. see this code which is polling for window.fdc3 on a timer: view-source:https://donbasuno.github.io/FDC3/toolbox/fdc3_explained.html
