### ISSUE TITLE
Allow Desktop Agent To Join Multiple Channels

### ISSUE THREAD

**Issue by sgd2z** [ChartIQ/FDC3#6]
## Enhancement Request

We would like to propose allowing the desktop agent to join multiple channels.

### Use Case:
![image](https://user-images.githubusercontent.com/18012933/93239243-8213c700-f750-11ea-85e7-ee81fb821dfd.png)

Note the screenshot above. Here two blotters (let's say portfolio views) are sharing the same chart and news content. These portfolio views are themselves driven by different account views.

### Workflow Description and Example:
- User links one account view to one portfolio view on the green channel (so when the user switches to another account, the portfolio switches to that account)
- User links a second account view to a second portfolio view on the red channel
- User links charts and news on both red channel and green channel (so clicking on a symbol in either portfolio changes the chart and news to that symbol)

### Additional Information
This would require the following API additions
```
leaveChannel(channelId: string) : Promise<void>;
getCurrentChannels() : Promise<void>;
```
and following API removals
```
leaveCurrentChannel() : Promise<void>;
getCurrentChannel() : Promise<void>;
```

**Comment by kriswest** [comment]
Fixed a minor type, LGTM
